"""entries table

Revision ID: da058a581050_
Revises: 
Create Date: 2023-05-16 11:11:08.538451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae402c51a54a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('bankAccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountName', sa.String(length=120), nullable=True),
    sa.Column('customerId', sa.Integer(), sa.ForeignKey("customers.id"), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False, default = 'EUR'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromAccountId', sa.Integer(),sa.ForeignKey("bankAccounts.id"), nullable=False),
    sa.Column('toAccountId', sa.Integer(),sa.ForeignKey("bankAccounts.id"), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###
       # insert customer records 
    # op.bulk_insert(
    #     'customers',
    #     [
    #         {'id':1, 'name': 'Arisha Barron'},
    #         {'id':2, 'name': 'Branden Gibson'},
    #         {'id':3, 'name': 'Rhonda Church'},
    #         {'id':4, 'name': 'Georgina Hazel'},
    #     ]
    # )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='public')
    op.drop_table('transactions', schema='public')
    op.drop_table('customers', schema='public')
    op.drop_table('bankAccounts', schema='public')
    # ### end Alembic commands ###
